### ISSUE TITLE
support botocore-1.34.53?

### ISSUE THREAD

**Issue by rohit901** [aio-libs/aiobotocore#1095]
Could you please support botocore-1.34.53 

Im getting this error: aiobotocore 2.12.0 requires botocore<1.34.52,>=1.34.41, but you have botocore 1.34.53 which is incompatible.

**Comment by Ranjith072** [comment]
i have the same problem ..i have a schedule that runs on the first day of the every month to update all the aws packages and every other aws packages almost support the latest version except this one ..could you please try to make a release to support the latest versions of other aws packages like (botocore, boto3, awscli etc).

**Comment by jakob-keller** [comment]
Thanks for using aiobotocore!

Due to the way we integrate with botocore, there will always be a gap between their most recent release and the latest version we have reviewed and approved. See also #1089

We aim to keep that gap small, but your dependency management and/or CI should take that into account to avoid running into the sort of issues you are experiencing.

What prevents you from working with botocore==1.34.51 until we ship a new release?
