### ISSUE TITLE
Error uploading file in us-west-2

### ISSUE THREAD

**Issue by jaymell** [aio-libs/aiobotocore#126]
Hello. I get an error when trying to upload to a bucket in us-west-2 region. This script works without issue if I upload to a bucket in us-east-1 :

```
Traceback (most recent call last):
  File "async-s3-2.py", line 28, in <module>
    event_loop.run_until_complete(main(event_loop, '/tmp/test_file'))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "async-s3-2.py", line 21, in main
    await write_to_s3(loop, f)
  File "async-s3-2.py", line 15, in write_to_s3
    Body=b'\x01'*1024)
  File "/usr/local/lib/python3.5/dist-packages/aiobotocore/client.py", line 91, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (TemporaryRedirect) when calling the PutObject operation: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
```

Encountered this error with version '0.2.1'

Code is largely copied from example:
```
async def write_to_s3(loop, f):
  bucket = 'my-bucket'
  sess = aiobotocore.get_session(loop=loop)
  async with sess.create_client('s3', region_name='us-west-2',
    aws_secret_access_key='xxx,
    aws_access_key_id='xxx') as cli:
    resp = await cli.put_object(Bucket=bucket, 
                                   Key=f,
                                   Body=b'\x01'*1024)
```

**Comment by hellysmile** [comment]
Seems Your bucket was created in another region, then You are trying to access

**Comment by thehesiod** [comment]
can you check to see if it works in botocore?

**Comment by jaymell** [comment]
I'm not sure what the issue was, but the script is working now without modification. Thanks for the quick response.

**Comment by pohmelie** [comment]
Have same issue, it looks like redirect wont work. http://docs.aws.amazon.com/AmazonS3/latest/dev/Redirects.html
The problem maybe gone since DNS propagated. Right now I have two hours since bucket created and got:
`botocore.exceptions.ClientError: An error occurred (TemporaryRedirect) when calling the GetObject operation: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.`

`botocore` itself works just fine. I see #116 here, but it is closed. :thinking:

**Comment by thehesiod** [comment]
this is the relevant line: https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/endpoint.py#L182  however I think it's incorrectly using a MultiDict instead of a CIMultiDict.  Oddly we have a unittest (https://github.com/aio-libs/aiobotocore/blob/master/tests/test_basic_s3.py#L391 IIRC) that's passing so either we need a new unittest or need to fix the unittest.

**Comment by pohmelie** [comment]
I did not dig deep into #116 much. Please, clarify me, is this problem solvable with `aiobotocore` changes or this require `aiohttp` changes too?

**Comment by thehesiod** [comment]
sorry updated my comment with correct location in endpoint.py, issue is most likely in aiobotocore
