### ISSUE TITLE
vendor botocore

### ISSUE THREAD

**Issue by graingert** [aio-libs/aiobotocore#142]
Currently aiobotocore and botocore are version locked, and new versions of botocore have been released.

This makes it impossible to install the latests versions of both awsclia and aiobotocore when using pip-compile (from pip-tools).

If you vendor (copy the source code into aiobotocore/_vendor/.../) it would be possible to use both in the same virtualenv without conflicts.

**Comment by graingert** [comment]
See https://github.com/aio-libs/aiobotocore/pull/141

**Comment by thehesiod** [comment]
I'm not sure this is so simple, botocore has its own requirements so technically you'd have to vendorize them as well.

**Comment by graingert** [comment]
@thehesiod that's ok because botocore depends on version ranges, and those can just be copied into the aiobotocore install_requires.

**Comment by thehesiod** [comment]
if you're going to use install_requires then you can just do that with botocore as well :)

**Comment by graingert** [comment]
?

**Comment by thehesiod** [comment]
your claim is that you'd like to be able to install latest awscli + aiobotocore together, and can't right now because awscli uses the latest botocore and aiobotocore hasn't patched to that version yet, so proposed solution is to vendor in botocore, however botocore has locked requirements.  Your proposed solution of adding these requirements to install_requires of aiobotocore has the same problem as the original because if you install awscli after aiobotocore it will overwrite the aiobotocore's install_requires with the latest dependencies of botocore.  There's no way around it, if you want to vendor in botocore you have to vendor in all its requirements as well.

**Comment by thehesiod** [comment]
The only way I see this of working is to always match awscli and aiobotocore with versions that have the same underlying botocore..if you need a newer version of aiobotocore that's fine, I'd open a issue and it can be done with not too much work.

**Comment by graingert** [comment]
False, botocore has unlocked dependencies

**Comment by thehesiod** [comment]
uhm https://github.com/boto/botocore/blob/develop/setup.py#L8

**Comment by graingert** [comment]
That looks unlocked to me

**Comment by thehesiod** [comment]
tell me what happens if next version of botocore changes python-dateutil to >= 4, or they change docutils to docutils>=0.10 <= 1.0 ?  it will break

IOW botocore depends on specific revisions of certain modules, and with a vendored botocore can and will break this workflow if you install aiobotocore with vendored botocore before the latest botocore.

**Comment by graingert** [comment]
Yeah but that's way less likely than botocore releasing a new minor version

**Comment by thehesiod** [comment]
broken is broken :)  If we're going to fix this I rather not do a half-baked solution.

**Comment by jettify** [comment]
I believe we can close this issue, now aiobotocore has relaxed constrains `'botocore>=1.5.0, <=1.5.33'`
