### ISSUE TITLE
pytest fixtures available for external projects

### ISSUE THREAD

**Issue by mkurek** [aio-libs/aiobotocore#583]
It would be great to have access to pytest fixtures defined in [conftest.py](https://github.com/aio-libs/aiobotocore/blob/master/tests/conftest.py) or [mock_server.py](https://github.com/aio-libs/aiobotocore/blob/master/tests/mock_server.py) in external projects which depend on aiobotocore. 

Similar setup is done for example in [aiohttp's pytest_plugin](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/pytest_plugin.py)

What do you think about it?

**Comment by thehesiod** [comment]
great idea, which ones in particular are you interested in?

**Comment by asvetlov** [comment]
Side note. 
It would be nice if public aiobotocore fixtures are prefixed with the project name, as we did it for `pytest-aiohttp`. Otherwise, a chance for naming conflict with other libs is high.

**Comment by mkurek** [comment]
Hi. Right now we're using only s3-related fixtures: `bucket_name`, `create_object` and `s3_server` (but they have a lot of dependent fixtures underneath).

**Comment by jettify** [comment]
Mock server is simple wrapper around moto library, it starts real network server on specified port, as result we have better test coverage since we do not have to use mocking. Probably https://github.com/jotes/pytest-moto is better fit for you, but library was not updated for some time. 

My point is that this fixture is not about aiobotocore and more about generic aws service substitution. We can easily create pytest plugin, but I suggest to give pytest-moto a try first.

**Comment by thehesiod** [comment]
I was going to close this in favor of pytest-moto, but I'm going to morph it into moving us to use pytest-moto, and contributing to it where it makes sense.
