### ISSUE TITLE
aiobotocore (0.9.3) released just a few days ago is already behind the latest botocore release

### ISSUE THREAD

**Issue by terrisgit** [aio-libs/aiobotocore#615]
> aiobotocore 0.9.3 has requirement botocore<1.10.59,>=1.10.58, but you'll have botocore 1.10.62 which is incompatible

AWS is releasing botocore almost every 3 days. There is no way for you to keep up with it.

I think the dependency should be something like < 1.11.0 instead of specifying a specific version.

Note that all python libraries have this issue. Nodejs projects too. Many are following a practice of allowing minor-minor upgrades to dependent packages without needing to release a new version.

Some languages (particularly java : jarjar, osgi [1]) address the issue of conflicting dependencies. Python is not one of them.

[1] https://stackoverflow.com/questions/37438559/how-can-i-resolve-jar-hell-without-using-a-heavy-weight-framework

**Comment by thehesiod** [comment]
You aren't understand what this library is or how it works.  It's essentially a giant monkeypatch around botocore.

we can't do ranges of versions because we are replacing internals of botocore, as noted in the latest release this meant what had to implement a counterpart async version.  We do not in this project want to support old versions of botocore as people should be moving forwards in botocore releases and not backwards and haven't heard of use-cases where this is important.  If you have another library that depends on botocore we can add it to extras so they get version locked together properly, that's what we have boto3 + awscli in there.

So if you want to use an old version of botocore, use an old version of aiobotocore

If you want to use a newer version of botocore, unfortunately for now you'll have to wait for a newer release of aiobotocore, or until botocore supports pluggable backends (please look at existing issues about this).  Note we update fairly often so this shouldn't be a big issue...further aiobotocore isn't meant to be bleeding edge.

sorry but as I see it this is a non-solvable issue for now given the other open issues. Please re-open if I'm not understanding something with this request.

**Comment by terrisgit** [comment]
Thanks for the education! awscli and cloudwatch were causing me problems.

So I have to do this:

> aiobotocore==0.9.3
> awscli==1.15.59
> boto3==1.7.58
> botocore==1.10.58
> watchtower<0.6.0  # 

For Cloudwatch logging

**Comment by thehesiod** [comment]
use extras :)
```
aiobotocore[awscli,boto3]==0.9.3
```

that will get you the right versions of botocore + awscli + boto3
