### ISSUE TITLE
Why is boto3 being pinned to a specific version?

### ISSUE THREAD

**Issue by rahul003** [aio-libs/aiobotocore#718]
**Describe the bug**
Looks like boto3 is now pinned to a specific version. Why was this done?

**Comment by terrycain** [comment]
Because boto3 will try and pull in a later non-tested version of botocore

**Comment by Vikas-kum** [comment]
@terrycain , is there a specific stable version of aioboto we can pin to ?
Our build keeps on breaking because of the dependency issue.
I don't know if there is any better way. I am thinking of pinning aiobotocore to a stable version and thus pinning boto3 and botocore to specific required version.

**Comment by thehesiod** [comment]
@Vikas-kum aioboto pins to aiobotocore: https://github.com/terrycain/aioboto3/blob/master/setup.py#L15 which pins boto3, I'm not sure what your issue is in particular

if you use aioboto/aiobotocore, you should depend on it for your boto3 pinning

**Comment by thehesiod** [comment]
boto3 is an _optional_ extra: https://github.com/aio-libs/aiobotocore/blob/master/setup.py#L30, which helps you use a compatible version that works with  the pinned version of botocore this library requires.  Going to close because this is a fact of life for this library, and in fact is (optionally) helping you,  see https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#background-and-implementation.  Please re-open if we're not understanding something.  Without this extra, if you were to pull in a different version of boto3/awscli it would not be guaranteed to be compatible.

**Comment by rahul003** [comment]
Is there a good way to handle the case when user has a different version of boto3 installed, but we need this pinned version? Is the only way ahead that we ask user to uninstall the older package?

**Comment by thehesiod** [comment]
But in a supported way. You can try and hope it works. Otherwise should pull deps from aioboto3/aiobotocore via extras
