### ISSUE TITLE
Why create_client returns context manager? 

### ISSUE THREAD

**Issue by kkopachev** [aio-libs/aiobotocore#787]
Mostly just curious, since 1.0 release, `create_client` method now required to be used as context manager with `async with`. 
Examples in docs were not updated, so that's a bit confusing. 

What I am trying to do is that I have Tornado app, which as part of it's bootstrap creates an instance of "s3_loader". I hope to use the same loader across multiple incoming requests, since configuration persists. 
With changes in 1.0 I have to use context manager for each attempt to use loader. Which is unfortunate, it would have to create new client every time and after each load request would have to spin it down, close http pool, etc. Seems inefficient? 

I looked at how you do it in tests, and it looks ugly. 
https://github.com/aio-libs/aiobotocore/blob/d7ca7ea7f0458bb60fc994304892da15a8edd885/tests/conftest.py#L204-L214

I'd hope to create client asynchronously first time my loader is used, store it in instance property and reuse on subsequent calls.

I probably can call `__aenter__` on first use, store result in a property and then be sure to call `__aexit__` in destructor. Seems too magic.

Is this by design and I am missing something very conceptual here?

**Comment by terrycain** [comment]
Just adding my 2cents here, I see no issue calling `__aenter__` and `__aexit__` in the setup and close functions of a webserver. You can see that aiobotocore does similar here

https://github.com/aio-libs/aiobotocore/blob/d7ca7ea7f0458bb60fc994304892da15a8edd885/aiobotocore/client.py#L254-L259

**Comment by kkopachev** [comment]
I saw this too, but that piece of code belongs to definition of outer context manager, so kind of makes sense to call "super" enter/exit methods. It's like inheritance, where child method calls parent method. 

In my case, I'd have to call these magic methods by themselves outside of context manager, which looks confusing and create extra complexity while reading the code. It does not feel natural. Too much of perfection to ask, maybe? :man_shrugging:

**Comment by thehesiod** [comment]
partially due to what @terrycain said, but also because we now need to call an async method (emit) before creating the client so we need to tie the two together in a context manager to avoid "ugliness". Also in general you should always use context manager because you need to close the related http session.  Really it should have always been a context manager.  If you're running an async web-server like aiohttp you should put the client in an https://docs.python.org/3/library/contextlib.html#contextlib.AsyncExitStack and call the exit_stack's `__aexit__` during the cleanup method during the server shutdown.  I'll fix the docs in https://github.com/aio-libs/aiobotocore/pull/792

**Comment by thehesiod** [comment]
@kkopachev  so it would look like:
```python
self._client = await self._exit_stack.enter_async_context(aioboto_session.create_client('s3'))
```

**Comment by terrycain** [comment]
@thehesiod  would it make sense to add an example of using AsyncExitStack in the docs?

**Comment by thehesiod** [comment]
Sure

**Comment by thehesiod** [comment]
@kkopachev  actually that's not the best example btw, those fixtures should be re-written to use contexts as well, see: https://github.com/aio-libs/aiobotocore/blob/master/tests/conftest.py#L373
