### ISSUE TITLE
python 3.6 support for access to the event loop on a session

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#788]
https://github.com/aio-libs/aiobotocore/commit/01269ab8c5e886546d3d32991772cfefa0eebfd2 removed the option to manage an event loop, which seems to make things harder on python 3.6.  It seems to be essential to have some way to access to the aiohttp event loop for some operations where the current event loop is modified without it becoming the default event loop (e.g. pytest-asyncio) or when a new event loop is created but it cannot run any new coroutines using an existing aio-session that was created with a different loop.

Until there is some kind of backport for `asyncio.run` to python 3.6, it would be useful to have something like `session.get_loop()` maybe so that the aiohttp loop can be surfaced.  I'm looking for some kind of backport of `asyncio.run` but all I've found so far is a gist at
https://gist.github.com/nickdavies/4a37c6cd9dcc7041fddd2d2a81cee383

**Comment by thehesiod** [comment]
in python 3.6 you don't need to use event loop either, you should always be using asyncio.get_event_loop() if you need it as there's always been a 1-1 relationship between the active loop and a thread.  You should create the aiobotocore session + client when the same loop you'll be using them from is active.  Otherwise things will never work 100% correctly as there is a lot of "bad" code that gets the loop via get_event_loop even if you pass in the loop....this is why they just got rid of it in most places as it led to many bugs.  And btw we've found a few issues with asyncio.run so be careful there as well :) Going to close as I believe this is as-designed, but if you feel strongly feel free to re-open.
