### ISSUE TITLE
aiohttp 1.2+ ClientSession issues

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiobotocore#85]
ERROR [asyncio] Creating a client session outside of coroutine

due

https://github.com/KeepSafe/aiohttp/blob/c4539a7f3851483c985fa885f7e4a151e3bc3d43/aiohttp/client.py#L57

I can propose to implement lazy(on_demand) _aio_session initialization, if it is ok, I'll make pull request

**Comment by asvetlov** [comment]
Please no.
Explicit session lifetime is better than implicit one.
If you initialize a session on demand -- when do you finalize it? Lazy cleanup scares me.

The change is made for forcing the rule: lifetime of async objects should be shorter than event loop run time.

Right now aiohttp doesn't raise exception but a warning.
I guarantee this behavior will be not changed for 1.5 years at least.

**Comment by jettify** [comment]
@asvetlov thanks for clarification, closing

**Comment by KaiPetzke** [comment]
I recommend re-opening this issue and re-thinking the decision made. My reason for this is, that with Python 3.5, we got the: "async with" syntax for asynchronous context managers. Session lifetime is determined by the time span between calling the __aenter__ coroutine and calling the __aexit__ coroutine. On the other hand, session managers can be created by outside context synchronously.

See PEP 492 and the examples in there. Especially this one:
    async with lock:

"lock" is (synchronously) created by outside called, while "async with" (which then calls lock.__aenter__) is only callable from within the event loop. Actually, "async with lock" can be executed many times for the same lock.

The same should be possible for aiohttp. So aiohttp.ClientSession() should do nothing but create a ClientSessionManager. Then the __aenter__ method of the ClientSessionManager ought to do all the necessary resource acquisition (namely create a connector), and __aexit__ should tidy up again. It should also be possible to call __aenter__ and __aexit__ repeatedly, so __aenter__ should reopen a previously closed ClientSession, respectively create a new one. Only the object returned from __aenter__ should allow methods like request() or get().

Note, that you already follow the asynchronous session manager semantics for methods like request() or get(): Both request() and get() are synchronous methods, that do nothing but create a requestContextManager. In particular, they don't yield or await anything. They just store a reference to the coroutine, that will later - during the call to _aenter__ - asynchronously create the connection.

In my opinion, the same semantics, that get() and request() use, should also be used for aiohttp.ClientSession()

So, the following SHOULD work fine in my opinion:

class aiohttp_user:
    def __init__(self):
        self.clientsession = aiohttp.ClientSession()

    async def method(self, url):
        async with self.clientsession as client:
            async with cient.get(url) as request:
                ...

So, if some of the connections inside method() fail due to nasty server behaviour (timeouts, wrong answers etc.), the surrounding code can later retry calling method(), which will then re-start with a fresh connection pool, but otherwise with saved state (like cookies, partially retrieved data etc.).


In many cases, classes, that use aiohttp will be session managers themselves. Implementing that looks a bit ugly in Python:

class aiohttp_user:
    def __init__(self):
        self.clientsession = aiohttp.ClientSession()

    def __aenter__(self):
        try:
            self.client = await self.clientsession.__aenter__()
        catch:
            # tidy up, whatever needs to be tidied up (__aexit__ won't be called automtically!)
            throw

    def __aexit__(self, *args, **kwargs):
        flag = self.clientsession.__aexit__(*args, **kwargs)
        # Do further tidying up
        return flag

    async def method(self, url):
        async with cient.get(url) as request:
            ...

Currently, the above code doesn't work: It yields the nasty warning, that the whole discussion here is about, and it will even fail, if an object generated from aiohttp_user is used twice or more times inside "async with".

When changing the code, please keep in mind, that long-term ressources (like CookieJar etc.) should be bound to the persistent, non-async ClientSession (which is actually a ClientSessionManager), while volatile ressources (like the actual socket connection pool etc.) should be bound to the object, that is created upon call to ClientSession.__aenter__().
