### ISSUE TITLE
Remove  `_register_lazy_block_unknown_fips_pseudo_regions`

### ISSUE THREAD

**Issue by crispinlogan** [aio-libs/aiobotocore#900]
**Describe the bug**
Remove `_register_lazy_block_unknown_fips_pseudo_regions` from [AioClientCreator](https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/client.py#L18) in client.py. Why? `_register_lazy_block_unknown_fips_pseudo_regions` was intentionally removed from `botocore` (and AioClientCreator inherits from `botocore`'s ClientCreator, where _register_lazy_block_unknown_fips_pseudo_regions was originally defined) as it was used for testing purposes only, and seems to have been added to `aiobotocore` inadvertently, so now that it has been removed from `botocore`, it should also be removed from `aiobotocore`, otherwise you will get a `AttributeError: _register_lazy_block_unknown_fips_pseudo_regions attribute does not exist` type error.

This [comment](https://github.com/boto/botocore/issues/2568#issuecomment-970484165) on an issue in `botocore` also explains the issue and gives some more context.

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: [e.g. 3.6]
 - OS name and version: [e.g. darwin stretch]

**Additional context**

**Comment by mazzma12** [comment]
I have the same issue with the versions:

**Comment by ctippur** [comment]
Does this issue involve to_csv() as well?
Looks like the call is not writing to S3. I dont see any errors either.

**Comment by NeilJonkers** [comment]
No,  `to_csv()` is not impacted by this issue.

**Comment by thehesiod** [comment]
this is not a bug, aiobotocore 1.4.2 is tied to botocore 1.17.106: https://github.com/aio-libs/aiobotocore/blob/1.4.2/setup.py#L10. This strong tie is due to how aiobotocore is implemented. If you'd like to use a newer botocore you need to swap to aiobotocore 2.x

**Comment by thehesiod** [comment]
please re-open if I'm missing something

**Comment by hayashier** [comment]
Sorry for reopening this issue.

I investigated this issue and found this issue is caused by the following change in botocore 1.23.0.

- [Adding modeled endpoint variants support #2558](https://github.com/boto/botocore/pull/2558)

aiobotocore 2.0.1 corresponds to botocore 1.22.8. So in order to resolve this issue, I confirmed aiobotocore should bump to botocore 1.23.0 or later(For example, 1.23.14)
https://github.com/aio-libs/aiobotocore/blob/2.0.1/setup.py#L10
```
'botocore>=1.22.8,<1.22.9',
```

So I opened the issue which requests to bump to botocore 1.23.0 or later.

- [bump to botocore 1.23.0 or later](https://github.com/aio-libs/aiobotocore/issues/904 )

Thanks,

**Comment by hayashier** [comment]
# Details
The caller of aiobotocore is at the following location.
https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/client.py#L46
```
self._register_lazy_block_unknown_fips_pseudo_regions(service_client)
```

This corresponds to the following function in the parent class botocore.
https://github.com/boto/botocore/blob/1.22.8/botocore/client.py#L102
```
self._register_lazy_block_unknown_fips_pseudo_regions(service_client)
```

In botocore 1.23.0 and later, the above line has been removed and the following line has been added in its place.
This corresponds to the following function in the parent class botocore.
https://github.com/boto/botocore/blob/1.23.0/botocore/client.py
```
region_name, client_config = self._normalize_fips_region(
    region_name, client_config)
```


So I confirmed this issue was resolved by patching the following diff. Actually, according to the [Contributing](https://aiobotocore.readthedocs.io/en/latest/contributing.html ) policy, it seems that aiobotocore needs to be updated entirely to match the version of botocore.

```
diff --git a/aiobotocore/client.py b/aiobotocore/client.py
index 5dee865..13cf364 100644
--- a/aiobotocore/client.py
+++ b/aiobotocore/client.py
@@ -28,6 +28,8 @@ class AioClientCreator(ClientCreator):
         service_name = first_non_none_response(responses, default=service_name)
         service_model = self._load_service_model(service_name, api_version)
         cls = await self._create_client_class(service_name, service_model)
+        region_name, client_config = self._normalize_fips_region(
+            region_name, client_config)
         endpoint_bridge = ClientEndpointBridge(
             self._endpoint_resolver, scoped_config, client_config,
             service_signing_name=service_model.metadata.get('signingName'))
@@ -42,7 +44,6 @@ class AioClientCreator(ClientCreator):
         self._register_endpoint_discovery(
             service_client, endpoint_url, client_config
         )
-        self._register_lazy_block_unknown_fips_pseudo_regions(service_client)
         return service_client
 
     async def _create_client_class(self, service_name, service_model):
diff --git a/setup.py b/setup.py
index 9d8d0c3..c69296a 100644
--- a/setup.py
+++ b/setup.py
@@ -7,7 +7,7 @@ from setuptools import setup, find_packages
 # NOTE: When updating botocore make sure to update awscli/boto3 versions below
 install_requires = [
     # pegged to also match items in `extras_require`
-    'botocore>=1.22.8,<1.22.9',
+    'botocore>=1.23.13,<1.23.14',
     'aiohttp>=3.3.1',
     'wrapt>=1.10.10',
     'aioitertools>=0.5.1',
@@ -19,8 +19,8 @@ def read(f):
 
 
 extras_require = {
-    'awscli': ['awscli>=1.21.8,<1.21.9'],
-    'boto3': ['boto3>=1.19.8,<1.19.9'],
+    'awscli': ['awscli>=1.22.13,<1.22.14'],
+    'boto3': ['boto3>=1.20.13,<1.20.14'],
 }  
```

**Comment by hayashier** [comment]
I couldn't reopen that issue(only repo owner or collaborator can reopen as far as I know), so I created the same issue newly.
https://github.com/aio-libs/aiobotocore/issues/905

**Comment by MisSwa** [comment]
this is affecting to_csv() as well
