### ISSUE TITLE
Bump botocore

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#993]
started work in https://github.com/aio-libs/aiobotocore/pull/974 however needs research into new async codepaths

**Comment by ppena-LiveData** [comment]
NOTE: this only bumps from `botocore>=1.27.59,<1.27.60` to `botocore>=1.27.92,<1.27.93`, but that's not new enough to work with the new AWS IAM Identity Center SSO login and only works with the old AWS Single Sign-On, so `botocore` is always showing me `SSOTokenLoadError('Error loading SSO Token: The SSO access token has either expired or is otherwise invalid.')`, even though the token is not expired. How hard would it be to bump `botocore` to be >=1.29 (or whatever version adds support for AWS IAM Identity Center)?

**Comment by thehesiod** [comment]
we need to finish this one first, because there's a new async codepath, then we can do further bumps.  Unfortunately it's a lot of work when they expose new codepaths that make network requests
